[project]
name = "fmp"
version = "0.1.0"
description = "fans656's media player"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fans>=0.0.51",
    "mpv>=1.0.7",
    "pyside6>=6.8.2.1",
]
